//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceForge.Vulcan.Tray {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Icons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Icons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SourceForge.Vulcan.Tray.Icons", typeof(Icons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon Blank {
            get {
                object obj = ResourceManager.GetObject("Blank", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon BuildFail01 {
            get {
                object obj = ResourceManager.GetObject("BuildFail01", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon BuildFail02 {
            get {
                object obj = ResourceManager.GetObject("BuildFail02", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon BuildFail03 {
            get {
                object obj = ResourceManager.GetObject("BuildFail03", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon BuildFail04 {
            get {
                object obj = ResourceManager.GetObject("BuildFail04", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon BuildFail05 {
            get {
                object obj = ResourceManager.GetObject("BuildFail05", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon BuildFail06 {
            get {
                object obj = ResourceManager.GetObject("BuildFail06", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon BuildFail07 {
            get {
                object obj = ResourceManager.GetObject("BuildFail07", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon BuildFail08 {
            get {
                object obj = ResourceManager.GetObject("BuildFail08", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon BuildFail09 {
            get {
                object obj = ResourceManager.GetObject("BuildFail09", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon BuildFail10 {
            get {
                object obj = ResourceManager.GetObject("BuildFail10", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon BuildFail11 {
            get {
                object obj = ResourceManager.GetObject("BuildFail11", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon BuildFail12 {
            get {
                object obj = ResourceManager.GetObject("BuildFail12", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon BuildFail13 {
            get {
                object obj = ResourceManager.GetObject("BuildFail13", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon BuildFail14 {
            get {
                object obj = ResourceManager.GetObject("BuildFail14", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon BuildFail15 {
            get {
                object obj = ResourceManager.GetObject("BuildFail15", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon BuildFail16 {
            get {
                object obj = ResourceManager.GetObject("BuildFail16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon BuildPass01 {
            get {
                object obj = ResourceManager.GetObject("BuildPass01", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon BuildPass02 {
            get {
                object obj = ResourceManager.GetObject("BuildPass02", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon BuildPass03 {
            get {
                object obj = ResourceManager.GetObject("BuildPass03", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon BuildPass04 {
            get {
                object obj = ResourceManager.GetObject("BuildPass04", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon BuildPass05 {
            get {
                object obj = ResourceManager.GetObject("BuildPass05", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon BuildPass06 {
            get {
                object obj = ResourceManager.GetObject("BuildPass06", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon BuildPass07 {
            get {
                object obj = ResourceManager.GetObject("BuildPass07", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon BuildPass08 {
            get {
                object obj = ResourceManager.GetObject("BuildPass08", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon BuildPass09 {
            get {
                object obj = ResourceManager.GetObject("BuildPass09", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon BuildPass10 {
            get {
                object obj = ResourceManager.GetObject("BuildPass10", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon BuildPass11 {
            get {
                object obj = ResourceManager.GetObject("BuildPass11", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon BuildPass12 {
            get {
                object obj = ResourceManager.GetObject("BuildPass12", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon BuildPass13 {
            get {
                object obj = ResourceManager.GetObject("BuildPass13", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon BuildPass14 {
            get {
                object obj = ResourceManager.GetObject("BuildPass14", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon BuildPass15 {
            get {
                object obj = ResourceManager.GetObject("BuildPass15", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon BuildPass16 {
            get {
                object obj = ResourceManager.GetObject("BuildPass16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Fail {
            get {
                object obj = ResourceManager.GetObject("Fail", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Pass {
            get {
                object obj = ResourceManager.GetObject("Pass", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
