package net.sourceforge.vulcan.mojo;

import java.util.Properties;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;

import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;

/**
 * @goal generate-version-properties
 * @phase generate-resources
 */
public class GenerateVersionPropertiesMojo	extends AbstractMojo {
	/**
	 * @parameter expression="${project.build.directory}/version.properties"
	 * @required
	 */
	private File versionFile;
	
	/**
	 * @parameter
	 * @required
	 */
	private String versionLabel;
	
	public void execute() throws MojoExecutionException	{
		final File dir = versionFile.getParentFile();
		if (!dir.exists() && !dir.mkdirs()) {
			throw new MojoExecutionException("Failed to create directory " + versionFile.getParent());
		}
		
		getLog().info("Writing version properties to " + versionFile.getAbsolutePath());
		
		Properties props = new Properties();
		props.setProperty("version", versionLabel.replaceAll("-SNAPSHOT", "").replaceAll("null", "0"));
		
		Writer writer = null;

		try {
			writer = new FileWriter(versionFile);

			props.store(writer, "generated by maven2");
		} catch (IOException e) {
			throw new RuntimeException(e);
		} finally {
			if (writer != null) {
				try {
					writer.close();
				} catch (IOException ignore) {
				}
			}
		}
	}
}
