<?xml version="1.0" encoding="UTF-8" ?>

<html
	xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US"
	xmlns:jsp="http://java.sun.com/JSP/Page"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:html="http://struts.apache.org/tags-html"
	xmlns:spring="http://www.springframework.org/tags"
	xmlns:v="http://vulcan.sourceforge.net/j2ee/jsp/tags">

<html:xhtml/>

<body>
	<v:messages/>
	
	<p>This section allows you to link to reports that are generated by your build process.
	For each report defined here, if the file is available in the build directory, a link
	will appear in the reports section of the build details for the project.</p>
	
	<c:url var="action" value="/admin/setup/saveArtifactLocations.do"/>
	
	<form action="${action}" method="post">
		<div class="build-reports" id="mousecoords">
			<table id="reports-list">
				<caption>Reports</caption>
				<tbody>
					<tr class="hidden" id="prototype">
						<td class="name">${item.name}</td>
						<td class="desc">${item.description}</td>
						<td class="buttons">
							<button type="button" class="edit" title="Edit">Edit</button>
							<button type="button" class="remove" title="Remove">Remove</button>
							<input type="hidden" name="prototype_name" class="name" value=""/>
							<input type="hidden" name="prototype_desc" class="desc" value=""/>
							<input type="hidden" name="prototype_path" class="path" value=""/>
						</td>
					</tr>
					<c:forEach items="${stateManager.config.artifactLocations}" var="item">
						<tr>
							<td class="name">${item.name}</td>
							<td class="desc">${item.description}</td>
							<td class="buttons">
								<button type="button" class="edit" title="Edit">Edit</button>
								<button type="button" class="remove" title="Remove">Remove</button>
								<input type="hidden" name="name" class="name" value="${item.name}"/>
								<input type="hidden" name="desc" class="desc" value="${item.description}"/>
								<input type="hidden" name="path" class="path" value="${item.path}"/>
							</td>
						</tr>
					</c:forEach>
					<tr class="new" id="insertion-point">
						<td colspan="2"><c:out value=""/></td>
						<td class="buttons">
							<button type="button" class="add">New</button>
						</td>
					</tr>
					<tr class="new">
						<td colspan="3"><button type="submit">Save</button></td>
					</tr>
				</tbody>
			</table>
		
			<table id="buildReportEditFields" class="hidden">
				<caption>Edit Report</caption>
				<tbody>
					<tr>
						<th>Name</th>
						<td><input type="text" id="artifact_name"/></td>
					</tr>
					<tr>
						<th>Description</th>
						<td><input type="text" id="artifact_desc"/></td>
					</tr>
					<tr>
						<th>Path</th>
						<td><input type="text" id="artifact_path"/></td>
					</tr>
					<tr>
						<td colspan="2">
							<button type="button" id="artifact_save">Ok</button>
							<button type="button" id="artifact_cancel">Cancel</button>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</form>
	
	<script type="text/javascript">
		function editArtifact(e) {
			var name = "";
			var desc = "";
			var path = "";
			var caption = "Edit Build Report";
			
			if ($(this).hasClass("add")) {
				window.artifactRow = null;
				caption = "Add New Build Report";
			} else {
				var row = $($(this).parents("tr").get(0));
				name = row.find("input.name").val();
				desc = row.find("input.desc").val();
				path = row.find("input.path").val();
				
				window.artifactRow = row;
			}
			
			$("#artifact_name").val(name);
			$("#artifact_desc").val(desc);
			$("#artifact_path").val(path);
			
			$("#buildReportEditFields caption").text(caption);
			$("#buildReportEditFields").fadeIn();
		}
		
		function dismissFields(e) {
			$("#buildReportEditFields").fadeOut();
		}
		
		function saveArtifact(e) {
			var row = window.artifactRow;
			if (row == null) {
				row = $("#prototype").clone(true);
				row.removeClass("hidden");
				row.find("input.name").attr("name", "name");
				row.find("input.desc").attr("name", "desc");
				row.find("input.path").attr("name", "path");
				$("#insertion-point").before(row);
			}
			
			row.find("td.name").text($("#artifact_name").val());
			row.find("td.desc").text($("#artifact_desc").val());
			
			row.find("input.name").val($("#artifact_name").val());
			row.find("input.desc").val($("#artifact_desc").val());
			row.find("input.path").val($("#artifact_path").val());
			
			return dismissFields(e);
		}
		
		function removeArtifact(e) {
			$($(this).parents("tr").get(0)).remove();
		}
		
		$(document).ready(function() {
			$("button.add").click(editArtifact);
			$("button.edit").click(editArtifact);
			$("button.remove").click(removeArtifact);
			
			$("#artifact_cancel").click(dismissFields);
			$("#artifact_save").click(saveArtifact);
			
			$("#reports-list").sortable({
				cursor: "move",
				items: "tr:not(.new)",
				revert: true,
				start: function(e, ui) {
					ui.helper.addClass("dragging");
				}
			});
		});
	</script>
</body>
</html>

