<?xml version="1.0" encoding="UTF-8" ?>

<html
	xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US"
	xmlns:jsp="http://java.sun.com/JSP/Page"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:html="http://struts.apache.org/tags-html"
	xmlns:spring="http://www.springframework.org/tags"
	xmlns:v="http://vulcan.sourceforge.net/j2ee/jsp/tags">

<html:xhtml/>

<body>
	<v:messages/>
	
	<p>This section allows you to link to reports that are generated by your build process.
	For each report defined here, if the file is available in the build directory, a link
	will appear in the reports section of the build details for the project.</p>
	
	<c:url var="action" value="/admin/setup/saveArtifactLocations.do"/>
	
	<form action="${action}" method="post">
		<v:bubble>
			<span class="caption">Reports</span>
			<ul id="reports-list">
				<li class="hidden" id="prototype">
					<span class="buttons">
						<button type="button" class="edit" title="Edit">Edit</button>
						<button type="button" class="remove" title="Remove">Remove</button>
						<input type="hidden" name="prototype_name" class="name" value=""/>
						<input type="hidden" name="prototype_desc" class="desc" value=""/>
						<input type="hidden" name="prototype_path" class="path" value=""/>
					</span>
					<span class="name">${item.name}</span>
					<span class="desc">${item.description}</span>
				</li>
				<c:forEach items="${stateManager.config.artifactLocations}" var="item">
					<li>
						<span class="buttons">
							<button type="button" class="edit" title="Edit">Edit</button>
							<button type="button" class="remove" title="Remove">Remove</button>
							<input type="hidden" name="name" class="name" value="${item.name}"/>
							<input type="hidden" name="desc" class="desc" value="${item.description}"/>
							<input type="hidden" name="path" class="path" value="${item.path}"/>
						</span>
						<span class="name">${item.name}</span>
						<span class="desc">${item.description}</span>
					</li>
				</c:forEach>
			</ul>
			<div>
				<button type="button" class="add">Add</button>
				<button type="submit">Save</button>
			</div>
		</v:bubble>
		
		<div id="buildReportEditFields" class="hidden">
		<v:bubble>
		<table>
			<tbody>
				<tr>
					<th>Name</th>
					<td><input type="text" id="artifact_name"/></td>
				</tr>
				<tr>
					<th>Description</th>
					<td><input type="text" id="artifact_desc"/></td>
				</tr>
				<tr>
					<th>Path</th>
					<td><input type="text" id="artifact_path"/></td>
				</tr>
				<tr>
					<td colspan="2">
						<button type="button" id="artifact_save">Ok</button>
						<button type="button" id="artifact_cancel">Cancel</button>
					</td>
				</tr>
			</tbody>
		</table>
		</v:bubble>
		</div>
	</form>
	
	<script type="text/javascript">
		function editArtifact(e) {
			var name = "";
			var desc = "";
			var path = "";
			
			if ($(this).hasClass("add")) {
				window.artifactRow = null;
			} else {
				var row = $($(this).parents("li").get(0));
				name = row.find("input.name").val();
				desc = row.find("input.desc").val();
				path = row.find("input.path").val();
				
				window.artifactRow = row;
			}
			
			$("#artifact_name").val(name);
			$("#artifact_desc").val(desc);
			$("#artifact_path").val(path);
			
			$("#buildReportEditFields").fadeIn();
		}
		
		function dismissLightbox(e) {
			$("#buildReportEditFields").fadeOut();
		}
		
		function saveArtifact(e) {
			var row = window.artifactRow;
			if (row == null) {
				row = $("#prototype").clone(true);
				row.removeClass("hidden");
				row.find("input.name").attr("name", "name");
				row.find("input.desc").attr("name", "desc");
				row.find("input.path").attr("name", "path");
				$("#reports-list").append(row);
			}
			
			row.find("span.name").text($("#artifact_name").val());
			row.find("span.desc").text($("#artifact_desc").val());
			
			row.find("input.name").val($("#artifact_name").val());
			row.find("input.desc").val($("#artifact_desc").val());
			row.find("input.path").val($("#artifact_path").val());
			
			return dismissLightbox(e);
		}
		
		function removeArtifact(e) {
			$($(this).parents("li").get(0)).remove();
		}
		
		$(document).ready(function() {
			$("button.add").click(editArtifact);
			$("button.edit").click(editArtifact);
			$("button.remove").click(removeArtifact);
			
			$("#artifact_cancel").click(dismissLightbox);
			$("#artifact_save").click(saveArtifact);
			
			$("#reports-list").sortable({
				revert: true
			});
		});
	</script>
</body>
</html>

